### PR TITLE
Add trivial parametrization 523 which always return the LUT value

### PR DESCRIPTION
**Pull request by elusian**
This PR adds a new schema, called 523, which always returns the plain LUT value (it has method = 'ONE' and target = ratio for all relevant entries).

This is part of the work in PR cms-sw/cmssw#33622 and is needed for optionally estimating the covariance matrix elements when they were not stored in miniAOD

@AdrianoDee

### CODE REVIEW

**Comment by slava77** [comment]
what's the meaning of "523"?

I see that only CovarianceParameterization_version1 (phase1 variant) is updated, but not version0. Shouldn't this new feature be available for 2016/phase0 as well?

**Comment by elusian** [comment]
523 has no deeper meaning than being 1 more than the parametrization that was suggested at the beginning, and unused. As you meantioned in the sibling PR, we couldn't find the convention for numbering. The number is however easily changed.

As for Phase0, the default value of `covarianceVersion` in `PackedCandidate` makes them hard to support. Since covarianceVersion==0 can either mean "phase0" or "a candidate that had no track associated at AOD level", in phase0 `fallBackTrack` would create tracks even when it should not.

**Comment by slava77** [comment]
> 523 has no deeper meaning than being 1 more than the parametrization that was suggested at the beginning, and unused. As you meantioned in the sibling PR, we couldn't find the convention for numbering. The number is however easily changed.
> 

it looks like 523 is in the middle of the range of existing schema numbers. So, it's unclear if there may be already conflicts if there is need to revive this topic.
Let's try to understand the numbering scheme first or otherwise move clearly outside of the existing range.

> As for Phase0, the default value of `covarianceVersion` in `PackedCandidate` makes them hard to support. Since covarianceVersion==0 can either mean "phase0" or "a candidate that had no track associated at AOD level", in phase0 `fallBackTrack` would create tracks even when it should not.

isn't the version paired with `covarianceSchema_` enough to disambiguate wrt default?

**Comment by elusian** [comment]
> isn't the version paired with covarianceSchema_ enough to disambiguate wrt default?

As far as I can tell the `covarianceSchema_` is set only when adding the track properties, so it does not provide a difference between a `PackedCandidate` where the track was not stored and one that had not track at all.

**Comment by slava77** [comment]
only one covariance version can be used per job (limitations from `call_once` in `covarianceParameterization()`); version0 is used for 2016.
Don't you need support for this new feature for 2016 as well?

**Comment by elusian** [comment]
What I mean is that a PF Candidate with no track associated will be stored in miniAOD as a PackedCandidate with `covarianceVersion_ == 0`, `covarianceSchema_ == 0` and `hasTrackDetails() == false`. A low pt PF candidate with an associated track is instead stored in miniAOD as a PackedCandidate with `covarianceVersion_ == phase`, `covarianceSchema_ == 0` and `hasTrackDetails() == false`. 

For phase0 this means that there is no difference at all between a low pt candidate and a candidate with no track.

Before the LUT feature this was fine, as if `hasTrackDetails() == false` the code never used `covarianceVersion_`.
However, using the LUT one skips the `hasTrackDetails()` check. If we allowed phase0 to use the LUT we'd be unpacking a `reco::Track` even in cases where there was none in the AOD, which is clearly incorrect. 

We haven't found a way to support phase0 that avoids this issue.

**Comment by slava77** [comment]
> We haven't found a way to support phase0 that avoids this issue.

isn't the solution to read a packed cand, figure out which needs a fall-back, and update that candidate data member(s) so that `hasTrackDetails() == true`?

**Comment by elusian** [comment]
Maybe I'm misunderstanding, but the issue is that in case of phase0 we cannot figure out wether we should or should not fall-back to the LUT

**Comment by slava77** [comment]
> Maybe I'm misunderstanding, but the issue is that in case of phase0 we cannot figure out wether we should or should not fall-back to the LUT

Somewhat aside from my earlier comments:
Looking at https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/PhysicsTools/PatAlgos/plugins/PATPackedCandidateProducer.cc#L284
IIUC, the covarianceVersion is always set consistently for all candidates.
So, there should be no confusion which version to load, even if it's 0.

this is not the case for the lost tracks (PhysicsTools/PatAlgos/plugins/PATLostTracks.cc does not set the covariance to all).

**Comment by slava77** [comment]
> this is not the case for the lost tracks (PhysicsTools/PatAlgos/plugins/PATLostTracks.cc does not set the covariance to all).

#33790 should solve this for the future

For the older cases a consistent solution can still be found by making a copy of the lostTracks collection and setting a consistent value for all candidates by configuration.

**Comment by AdrianoDee** [comment]
The issue here is not to know which version to load but if the candidate do not have a track from the beginning (genuinely) or it had a track but was not stored because it was too low in pT. 

This happens for phase0/2016 candidates because the  `covarianceVersion_ ` is set to 0 whichever the candidate, while for the rest of Run2 data the `covarianceVersion_ ` is 0 only when the PF candidate did not have a track at all. 

From this the ambiguity that is unresolvable (unless we re-miniAOD 2016 data, that is not happening).

Run2 three categories:

1.  _Track with details_ `hasTrackDetails==True` (not interested in, already got them)
2. `hasTrackDetails==False` &&  `covarianceVersion_ !=0` (good for the LUT)
3. `hasTrackDetails==False` && `covarianceVersion_ ==0`   (not interested in, do not have a track)

2016 two categories: 

4. _Track with details_ `hasTrackDetails==True` (not interested in, already got them)
5. `hasTrackDetails==False` &&  `covarianceVersion_ ==0`  that includes both _2_ and _3_ from above 

The point is: we don't want anyway to estrapolate a covariance matrix for a PF candidate that did not have the track information in the first place. Do we?

**Comment by elusian** [comment]
> IIUC, the covarianceVersion is always set consistently for all candidates.

To answer to that, when a track exists you are correct but when it does not, you go into this branch https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/PhysicsTools/PatAlgos/plugins/PATPackedCandidateProducer.cc#L326-L336, which does not set it. This is why we say that `covarianceVersion_ == 0` may mean that a candidate does not have a track.

cms-sw/cmssw#33790 does help in enabling the LUT for all lostTracks, but is unrelated to the 2016 problem we are discussing here.

**Comment by slava77** [comment]
> > IIUC, the covarianceVersion is always set consistently for all candidates.
> 
> To answer to that, when a track exists you are correct but when it does not, you go into this branch https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/PhysicsTools/PatAlgos/plugins/PATPackedCandidateProducer.cc#L326-L336, which does not set it. This is why we say that `covarianceVersion_ == 0` may mean that a candidate does not have a track.
> 
> [cms-sw/cmssw#33790](https://github.com/cms-sw/cmssw/pull/33790) does help in enabling the LUT for all lostTracks, but is unrelated to the 2016 problem we are discussing here.

thanks for correcting me.
Looking up, in the `    if (ctrack) {` branch, doesn't the `else` happen exclusively for neutrals?

**Comment by slava77** [comment]
so far, it still looks like there is some good enough logic that could make the case of `covarianceVersion_ == 0` usable.
This seems like a good reason to add the parameterization to the version0 file as well
and not prevent ability to use phase0 completely for the newly proposed/discussed fall back track mechanism.

**Comment by slava77** [comment]
> called 523, which always returns the plain LUT value (it has method = 'ONE' and target = ratio for all relevant entries).

I looked at the content and see that components 01 and 12 have method = `zero` and target = `realValue`. Is there a good reason for this?
If the full covariance packing unpacking was going through method = `one` and target = `ratioToRef`, then I see a good reason to hardcode the behavior, which is essentially just the covariance from meanValue.

**Comment by elusian** [comment]
That is because the new parametrization started as a modification of others, and those parameters are set at (`zero`, `realValue`) for all parametrizations in the file.

As far as I can tell however these two elements are never used for packing or unpacking, as PackedCandidate only uses 00, 11, 22, 33, 44, 14, 23, 34 and ignores everything else.
https://github.com/cms-sw/cmssw/blob/master/DataFormats/PatCandidates/src/PackedCandidate.cc#L100-L107

**Comment by elusian** [comment]
From my understanding of the naming scheme 523 is the first free entry of the "low quality with pixel" block (513-768).
Is it ok? 
Other possibilities I can think of inside the scheme are 768 (256*3, last possible entry in the block) or starting a new block from 1025 just for the trivial parametrization.

As soon as we can decide a number I will also add the modification to the phase0 file.

**Comment by slava77** [comment]
> From my understanding of the naming scheme 523 is the first free entry of the "low quality with pixel" block (513-768).
> Is it ok?
> Other possibilities I can think of inside the scheme are 768 (256*3, last possible entry in the block) or starting a new block from 1025 just for the trivial parametrization.
> 
> As soon as we can decide a number I will also add the modification to the phase0 file.

I have a mild preference to 1025, but 523 would probably still work.

A phase0 file is still needed before this can be merged.

**Comment by elusian** [comment]
In the end we chose to go with 1025
This commit also adds the parametrization for phase0

**Comment by slava77** [comment]
+reconstruction

tested in cms-sw/cmssw#34446 
the last successful test was in
https://github.com/cms-sw/cmssw/pull/34446#issuecomment-892005599

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@slava77 , as this PR modifies the existing files so https://github.com/cms-sw/cmsdist/pull/7203 should be merged a long with cms-sw/cmssw#34446

**Comment by slava77** [comment]
> @slava77 , as this PR modifies the existing files so [cms-sw/cmsdist#7203](https://github.com/cms-sw/cmsdist/pull/7203) should be merged a long with [cms-sw/cmssw#34446](https://github.com/cms-sw/cmssw/pull/34446)

this PR extends the files with new histograms; the updated files are backward compatible.

**Pull request merged**
